# Generated by Django 2.1.5 on 2019-01-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
    ]
